### ISSUE TITLE
Error in combining features while building MSnSet from mzids in rfp6/code.R

### ISSUE THREAD

**Issue by Sjan1** [Sjan1/r-for-proteomics-tsl#1]
## Error after line #32:
 Error in rowsum.default(nna, group = group, reorder = reorder, na.rm = na.rm) : 
  incorrect length for 'group' 

## TRACEBACK:

10.
stop("incorrect length for 'group'") 
9.
rowsum.default(nna, group = group, reorder = reorder, na.rm = na.rm) 
8.
rowsum(nna, group = group, reorder = reorder, na.rm = na.rm) 
7.
rowsd(exprs(x), group = groupBy, reorder = TRUE, na.rm = na.rm) 
6.
featureCV(object, groupBy = groupBy, norm = cv.norm) 
5.
combineFeaturesV(object, groupBy, fun, cv, cv.norm, verbose, 
    ...) 
4.
combineFeatures(e, groupBy = fData(msnset)$accession, fun = sum) at funs.R#12
3.
rtslprot:::make_pep_MSnSet(mzid_files, fcol = "pepSeq") 
2.
FUN(newX[, i], ...) 
1.
apply(etab, 1, function(.etab) {
    filenames <- exp %>% filter(biorep == .etab[["biorep"]], 
        phenotype == .etab[["phenotype"]], treatment == .etab[["treatment"]]) %>% 
        select(name) ... 
____________________________
## AFTER RStudio RESTART

 Error in combineFeatures(e, fcol = fcol, fun = sum) : 
  argument "groupBy" is missing, with no default 

## TRACEBACK:

4.
combineFeatures(e, fcol = fcol, fun = sum) 
3.
rtslprot:::make_pep_MSnSet(mzid_files, fcol = "pepSeq") 
2.
FUN(newX[, i], ...) 
1.
apply(etab, 1, function(.etab) {
    filenames <- exp %>% filter(biorep == .etab[["biorep"]], 
        phenotype == .etab[["phenotype"]], treatment == .etab[["treatment"]]) %>% 
        select(name) ...

**Comment by LaurentGatto** [comment]
As mentioned by email, try to update `MSnbase` using `BiocManager::install()` (which will update all your packages). You might also need a more recent R version.

**Comment by Sjan1** [comment]
Sorted out! Installation of the appropriate versions has helped. Thanks.
